import { Student, SchoolProfile, StockItem, SchoolNotice, PoshanAaharEntry, AttendanceRecord } from '../types';

export const INITIAL_SCHOOL_PROFILE: SchoolProfile = {
  schoolNameMr: 'जिल्हा परिषद प्राथमिक शाळा, रांजणगाव (गणपती)',
  schoolNameEn: 'Zilla Parishad Primary School, Ranjangaon',
  udiseCode: '27251402201',
  center: 'रांजणगाव केंद्र क्र. १',
  taluka: 'शिरूर',
  district: 'पुणे',
  headmasterName: 'श्री. सुनील डी. गायकवाड (मुख्याध्यापक)',
  primaryCookingRate: 5.45,
  upperPrimaryCookingRate: 8.17,
};

export const INITIAL_STUDENTS: Student[] = [
  // Class 1 (Std 1)
  {
    id: 'std1-1',
    rollNo: 1,
    nameMr: 'आरव सचिन पाटील',
    nameEn: 'Aarav Sachin Patil',
    gender: 'boy',
    standard: 1,
    division: 'A',
    parentNameMr: 'सचिन बाळू पाटील',
    parentNameEn: 'Sachin Balu Patil',
    parentPhone: '9822101011',
  },
  {
    id: 'std1-2',
    rollNo: 2,
    nameMr: 'अनन्या गणेश शिंदे',
    nameEn: 'Ananya Ganesh Shinde',
    gender: 'girl',
    standard: 1,
    division: 'A',
    parentNameMr: 'गणेश तुकाराम शिंदे',
    parentNameEn: 'Ganesh Tukaram Shinde',
    parentPhone: '9822101012',
  },
  {
    id: 'std1-3',
    rollNo: 3,
    nameMr: 'ओंकार रमेश मोरे',
    nameEn: 'Omkar Ramesh More',
    gender: 'boy',
    standard: 1,
    division: 'A',
    parentNameMr: 'रमेश नामदेव मोरे',
    parentNameEn: 'Ramesh Namdev More',
    parentPhone: '9822101013',
  },
  {
    id: 'std1-4',
    rollNo: 4,
    nameMr: 'स्वरा विलास कदम',
    nameEn: 'Swara Vilas Kadam',
    gender: 'girl',
    standard: 1,
    division: 'A',
    parentNameMr: 'विलास मारुती कदम',
    parentNameEn: 'Vilas Maruti Kadam',
    parentPhone: '9822101014',
  },

  // Class 2 (Std 2)
  {
    id: 'std2-1',
    rollNo: 1,
    nameMr: 'सार्थक बाबासाहेब पवार',
    nameEn: 'Sarthak Babasaheb Pawar',
    gender: 'boy',
    standard: 2,
    division: 'A',
    parentNameMr: 'बाबासाहेब पवार',
    parentNameEn: 'Babasaheb Pawar',
    parentPhone: '9822101021',
  },
  {
    id: 'std2-2',
    rollNo: 2,
    nameMr: 'सान्वी संतोष जगताप',
    nameEn: 'Sanvi Santosh Jagtap',
    gender: 'girl',
    standard: 2,
    division: 'A',
    parentNameMr: 'संतोष जगताप',
    parentNameEn: 'Santosh Jagtap',
    parentPhone: '9822101022',
  },
  {
    id: 'std2-3',
    rollNo: 3,
    nameMr: 'विहान दत्तात्रय चव्हाण',
    nameEn: 'Vihan Dattatray Chavan',
    gender: 'boy',
    standard: 2,
    division: 'A',
    parentNameMr: 'दत्तात्रय चव्हाण',
    parentNameEn: 'Dattatray Chavan',
    parentPhone: '9822101023',
  },

  // Class 3 (Std 3)
  {
    id: 'std3-1',
    rollNo: 1,
    nameMr: 'आदित्य राहुल देशमुख',
    nameEn: 'Aditya Rahul Deshmukh',
    gender: 'boy',
    standard: 3,
    division: 'A',
    parentNameMr: 'राहुल देशमुख',
    parentNameEn: 'Rahul Deshmukh',
    parentPhone: '9822101031',
  },
  {
    id: 'std3-2',
    rollNo: 2,
    nameMr: 'प्रांजल संभाजी थोरात',
    nameEn: 'Pranjal Sambhaji Thorat',
    gender: 'girl',
    standard: 3,
    division: 'A',
    parentNameMr: 'संभाजी थोरात',
    parentNameEn: 'Sambhaji Thorat',
    parentPhone: '9822101032',
  },
  {
    id: 'std3-3',
    rollNo: 3,
    nameMr: 'रुद्र सुनील गायकवाड',
    nameEn: 'Rudra Sunil Gaikwad',
    gender: 'boy',
    standard: 3,
    division: 'A',
    parentNameMr: 'सुनील गायकवाड',
    parentNameEn: 'Sunil Gaikwad',
    parentPhone: '9822101033',
  },

  // Class 4 (Std 4)
  {
    id: 'std4-1',
    rollNo: 1,
    nameMr: 'ईश्वरी ज्ञानेश्वर काळे',
    nameEn: 'Ishwari Dnyaneshwar Kale',
    gender: 'girl',
    standard: 4,
    division: 'A',
    parentNameMr: 'ज्ञानेश्वर काळे',
    parentNameEn: 'Dnyaneshwar Kale',
    parentPhone: '9822101041',
  },
  {
    id: 'std4-2',
    rollNo: 2,
    nameMr: 'समर्थ प्रवीण भोसले',
    nameEn: 'Samarth Pravin Bhosale',
    gender: 'boy',
    standard: 4,
    division: 'A',
    parentNameMr: 'प्रवीण भोसले',
    parentNameEn: 'Pravin Bhosale',
    parentPhone: '9822101042',
  },

  // Class 5 (Std 5)
  {
    id: 'std5-1',
    rollNo: 1,
    nameMr: 'तन्वी अशोक वाघमारे',
    nameEn: 'Tanvi Ashok Waghmare',
    gender: 'girl',
    standard: 5,
    division: 'A',
    parentNameMr: 'अशोक वाघमारे',
    parentNameEn: 'Ashok Waghmare',
    parentPhone: '9822101051',
  },
  {
    id: 'std5-2',
    rollNo: 2,
    nameMr: 'यश अमोल सोनवणे',
    nameEn: 'Yash Amol Sonawane',
    gender: 'boy',
    standard: 5,
    division: 'A',
    parentNameMr: 'अमोल सोनवणे',
    parentNameEn: 'Amol Sonawane',
    parentPhone: '9822101052',
  },
  {
    id: 'std5-3',
    rollNo: 3,
    nameMr: 'वेदांत किरण साळुंके',
    nameEn: 'Vedant Kiran Salunke',
    gender: 'boy',
    standard: 5,
    division: 'A',
    parentNameMr: 'किरण साळुंके',
    parentNameEn: 'Kiran Salunke',
    parentPhone: '9822101053',
  },

  // Upper Primary Class 6 (Std 6)
  {
    id: 'std6-1',
    rollNo: 1,
    nameMr: 'रोहन विजय खरात',
    nameEn: 'Rohan Vijay Kharat',
    gender: 'boy',
    standard: 6,
    division: 'A',
    parentNameMr: 'विजय खरात',
    parentNameEn: 'Vijay Kharat',
    parentPhone: '9822101061',
  },
  {
    id: 'std6-2',
    rollNo: 2,
    nameMr: 'सायली दीपक शेळके',
    nameEn: 'Sayali Deepak Shelke',
    gender: 'girl',
    standard: 6,
    division: 'A',
    parentNameMr: 'दीपक शेळके',
    parentNameEn: 'Deepak Shelke',
    parentPhone: '9822101062',
  },

  // Class 7 (Std 7)
  {
    id: 'std7-1',
    rollNo: 1,
    nameMr: 'अनिकेत प्रकाश जाधव',
    nameEn: 'Aniket Prakash Jadhav',
    gender: 'boy',
    standard: 7,
    division: 'A',
    parentNameMr: 'प्रकाश जाधव',
    parentNameEn: 'Prakash Jadhav',
    parentPhone: '9822101071',
  },
  {
    id: 'std7-2',
    rollNo: 2,
    nameMr: 'वैष्णवी भरत कुंभार',
    nameEn: 'Vaishnavi Bharat Kumbhar',
    gender: 'girl',
    standard: 7,
    division: 'A',
    parentNameMr: 'भरत कुंभार',
    parentNameEn: 'Bharat Kumbhar',
    parentPhone: '9822101072',
  },

  // Class 8 (Std 8)
  {
    id: 'std8-1',
    rollNo: 1,
    nameMr: 'प्रतीक एकनाथ वाळुंज',
    nameEn: 'Pratik Eknath Walunj',
    gender: 'boy',
    standard: 8,
    division: 'A',
    parentNameMr: 'एकनाथ वाळुंज',
    parentNameEn: 'Eknath Walunj',
    parentPhone: '9822101081',
  },
  {
    id: 'std8-2',
    rollNo: 2,
    nameMr: 'दिशा मंगेश नलावडे',
    nameEn: 'Disha Mangesh Nalawade',
    gender: 'girl',
    standard: 8,
    division: 'A',
    parentNameMr: 'मंगेश नलावडे',
    parentNameEn: 'Mangesh Nalawade',
    parentPhone: '9822101082',
  },
];

export const INITIAL_STOCK: StockItem[] = [
  {
    id: 'rice',
    nameMr: 'तांदूळ (FCI Grade-A)',
    nameEn: 'Rice (Govt Allotted)',
    unit: 'kg',
    openingStock: 85.5,
    receivedStock: 50.0,
    consumedStock: 18.2,
    currentStock: 117.3,
    minAlertThreshold: 20.0,
  },
  {
    id: 'pulses',
    nameMr: 'मटकी / चवळी / तूर डाळ',
    nameEn: 'Pulses & Legumes',
    unit: 'kg',
    openingStock: 24.0,
    receivedStock: 15.0,
    consumedStock: 4.5,
    currentStock: 34.5,
    minAlertThreshold: 8.0,
  },
  {
    id: 'oil',
    nameMr: 'खाद्यतेल (फोर्टिफाइड)',
    nameEn: 'Fortified Cooking Oil',
    unit: 'kg',
    openingStock: 10.0,
    receivedStock: 5.0,
    consumedStock: 1.25,
    currentStock: 13.75,
    minAlertThreshold: 3.0,
  },
  {
    id: 'spices',
    nameMr: 'मीठ व मसाले',
    nameEn: 'Iodized Salt & Spices',
    unit: 'kg',
    openingStock: 6.0,
    receivedStock: 3.0,
    consumedStock: 0.5,
    currentStock: 8.5,
    minAlertThreshold: 2.0,
  },
  {
    id: 'eggs_fruits',
    nameMr: 'अंडी / केळी / चिक्की (पूरक आहार)',
    nameEn: 'Eggs / Fruits / Chikki',
    unit: 'नग (Nos)',
    openingStock: 40,
    receivedStock: 50,
    consumedStock: 35,
    currentStock: 55,
    minAlertThreshold: 15,
  },
];

export const INITIAL_NOTICES: SchoolNotice[] = [
  {
    id: 'notice-1',
    titleMr: 'पालक-शिक्षक सभा (PTA Meeting) आयोजन',
    titleEn: 'Parent-Teacher Association Meeting Notice',
    date: new Date().toISOString().split('T')[0],
    category: 'meeting',
    targetStandard: 'all',
    messageMr: 'सर्व पालकांना कळविण्यात येते की, चालू शैक्षणिक वर्षातील प्रथम पालक-शिक्षक सभा दिनांक शनिवार रोजी सकाळी १०:०० वाजता शाळेच्या सभागृहात आयोजित केली आहे. विद्यार्थ्यांच्या प्रगतीविषयी व पोषण आहाराविषयी चर्चा होणार असल्याने सर्व पालकांनी आवर्जून उपस्थित राहावे.\n\n- मुख्याध्यापक व शिक्षक वृंद',
    messageEn: 'All parents are requested to attend the Parent-Teacher Meeting scheduled for this Saturday at 10:00 AM in the school hall to discuss student progress and Poshan Aahar. Your presence is highly valued.\n\n- Headmaster & Staff',
    issuedBy: 'मुख्याध्यापक',
    isUrgent: false,
  },
  {
    id: 'notice-2',
    titleMr: 'शालेय पोषण आहार (PM POSHAN) पालक चव तपासणी',
    titleEn: 'School Mid-Day Meal Tasting by Parents',
    date: new Date().toISOString().split('T')[0],
    category: 'mdm',
    targetStandard: 'all',
    messageMr: 'शासनाच्या निर्देशानुसार शाळेतील पोषण आहाराची चव व दर्जा तपासण्यासाठी दररोज दोन पालकांना आमंत्रित करण्यात येत आहे. उत्सुक पालकांनी वर्गशिक्षकांशी संपर्क साधावा.\n\n- शालेय पोषण आहार समिती',
    messageEn: 'As per government directives, parents are welcome to visit and taste the daily mid-day meal to verify quality and hygiene. Please coordinate with class teachers.\n\n- MDM Committee',
    issuedBy: 'पोषण आहार समिती',
    isUrgent: false,
  },
  {
    id: 'notice-3',
    titleMr: 'अतिवृष्टी / स्थानिक सुट्टी सूचना',
    titleEn: 'Heavy Rain / Emergency Holiday Notice',
    date: new Date().toISOString().split('T')[0],
    category: 'holiday',
    targetStandard: 'all',
    messageMr: 'जिल्हाधिकारी कार्यालयाच्या आदेशानुसार मुसळधार पावसामुळे उद्या शाळेस सुट्टी जाहीर करण्यात आली आहे. पालकांनी पाल्याची काळजी घ्यावी आणि त्यांना घरीच सुरक्षित ठेवावे.\n\n- आदेशानुसार मुख्याध्यापक',
    messageEn: 'As per District Collector guidelines regarding heavy rainfall, school will remain closed tomorrow. Parents are advised to ensure children remain safely indoors.\n\n- By Order, Headmaster',
    issuedBy: 'मुख्याध्यापक',
    isUrgent: true,
  },
];
